### ISSUE TITLE
Fix tests 

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/terraform-polkadot-aws-node#2]

**Comment by shinyfoil** [comment]
Multiple issues found so far:

- incorrect role orgs not propagated
- check CI has CF creds for non-default tests
- ansible won't download roles that already exist between test cases running in parallel
```
TestValidator 2021-04-22T11:06:48-04:00 command.go:158: [WARNING]: - geometrylabs.polkadot_truth was NOT installed successfully: the
TestValidator 2021-04-22T11:06:48-04:00 command.go:158: specified role geometrylabs.polkadot_truth appears to already exist. Use
TestValidator 2021-04-22T11:06:48-04:00 command.go:158: --force to replace it.
```
- test did not bring over double quote strip, so it's looking for "http://"123.456.789.0":9933"

Enhancement for later: ingest network_settings blob to check all the endpoints

**Comment by shinyfoil** [comment]
Need to bring over all the changes from the ASG. Missing variables like skip_health_check
